dataset_path: ohjoonhee/HR-Bench-with-captions
dataset_kwargs:
  token: True
task: "hrbench8k_tqa"
test_split: hrbench_8k
output_type: generate_until
doc_to_visual: !function utils.hrbench_doc_to_visual
doc_to_text: !function utils.hrbench_doc_to_text
doc_to_messages: !function utils.hrbench_doc_to_messages
doc_to_target: "answer"
# The return value of process_results will be used by metrics
process_results: !function utils.hrbench_process_results
# Note that the metric name can be either a registed metric function (such as the case for GQA) or a key name returned by process_results
metric_list:
  - metric: single
    aggregation: !function utils.hrbench_aggregate_results
    higher_is_better: true
  - metric: cross
    aggregation: !function utils.hrbench_aggregate_results
    higher_is_better: true
  - metric: average
    aggregation: !function utils.hrbench_aggregate_results
    higher_is_better: true

lmms_eval_specific_kwargs:
  default:
    system_prompt: |
      You are an AI assistant that rigorously follows this response protocol:

      1. First, conduct a detailed analysis of the question. Consider different angles, potential solutions, and reason through the problem step-by-step. Enclose this entire thinking process within <think> and </think> tags.

      2. After the thinking section, provide a clear, concise, and direct answer to the user's question. Separate the answer from the think section with a newline.

      Ensure that the thinking process is thorough but remains focused on the query. The final answer should be standalone and not reference the thinking section.
    pre_prompt: ""
    post_prompt: ""